# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joehu's Site
email:
description: >- # this means to ignore newlines until "baseurl:"
  A site of an osu! player who became interested in coding.
twitter_username: username
github_username: Joehuu
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joseph Madamba"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Someone who likes fixing small things"
  links:
    - label: "Joehuu"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joehuu"
    - label: "Joehu#7148"
      icon: "fab fa-fw fa-discord"
      url: "/social#Discord"
    - label: "osu!"
      icon: "fas fa-fw fa-link"
      url: "https://osu.ppy.sh/users/8549835"
    - label: "MyAnimeList"
      icon: "fas fa-fw fa-link"
      url: "https://myanimelist.net/profile/Joehu"
    - label: "MyFigureCollection"
      icon: "fas fa-fw fa-link"
      url: "https://myfigurecollection.net/profile/Joehu"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Joehuu"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
